# Generated by Django 4.1.6 on 2023-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facial_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
